// js/data.js
// All 151 Generation 1 (Kanto) Pokemon, areas, balls, achievements.
// Type colors based on classic Pokemon series.

const TYPE_COLORS = {
  normal:   '#c0a878', fire:    '#f08030', water:   '#6890f0', grass:    '#78c850',
  electric: '#f8d030', ice:     '#98d8d8', fighting:'#c03028', poison:   '#a040a0',
  ground:   '#e0c068', flying:  '#a890f0', psychic: '#f85888', bug:      '#a8b820',
  rock:     '#b8a038', ghost:   '#705898', dragon:  '#7038f8', dark:     '#705848',
  steel:    '#b8b8d0', fairy:   '#ee99ac',
};
function tc(t) { return TYPE_COLORS[t] || '#888'; }

// Compact spec helper: P(id, name, type, rarity, catch, emoji)
function P(id, name, type, rarity, catchRate, emoji) {
  return { id, name, emoji, type, rarity, catchRate, color: tc(type) };
}

const POKEDEX = [
  P('bulbasaur',  'Bulbasaur',  'grass',    4, 0.20, '\u{1F331}'),
  P('ivysaur',    'Ivysaur',    'grass',    4, 0.18, '\u{1F33F}'),
  P('venusaur',   'Venusaur',   'grass',    5, 0.10, '\u{1F33A}'),
  P('charmander', 'Charmander', 'fire',     4, 0.20, '\u{1F525}'),
  P('charmeleon', 'Charmeleon', 'fire',     4, 0.18, '\u{1F525}'),
  P('charizard',  'Charizard',  'fire',     5, 0.10, '\u{1F409}'),
  P('squirtle',   'Squirtle',   'water',    4, 0.20, '\u{1F422}'),
  P('wartortle',  'Wartortle',  'water',    4, 0.18, '\u{1F422}'),
  P('blastoise',  'Blastoise',  'water',    5, 0.10, '\u{1F30A}'),
  P('caterpie',   'Caterpie',   'bug',      1, 0.55, '\u{1F41B}'),
  P('metapod',    'Metapod',    'bug',      2, 0.45, '\u{1F7E2}'),
  P('butterfree', 'Butterfree', 'bug',      3, 0.30, '\u{1F98B}'),
  P('weedle',     'Weedle',     'bug',      1, 0.55, '\u{1F41B}'),
  P('kakuna',     'Kakuna',     'bug',      2, 0.45, '\u{1F7E1}'),
  P('beedrill',   'Beedrill',   'bug',      3, 0.30, '\u{1F41D}'),
  P('pidgey',     'Pidgey',     'flying',   1, 0.55, '\u{1F426}'),
  P('pidgeotto',  'Pidgeotto',  'flying',   2, 0.40, '\u{1F426}'),
  P('pidgeot',    'Pidgeot',    'flying',   3, 0.28, '\u{1F985}'),
  P('rattata',    'Rattata',    'normal',   1, 0.55, '\u{1F400}'),
  P('raticate',   'Raticate',   'normal',   2, 0.42, '\u{1F400}'),
  P('spearow',    'Spearow',    'flying',   1, 0.55, '\u{1F426}'),
  P('fearow',     'Fearow',     'flying',   2, 0.40, '\u{1F985}'),
  P('ekans',      'Ekans',      'poison',   2, 0.45, '\u{1F40D}'),
  P('arbok',      'Arbok',      'poison',   3, 0.30, '\u{1F40D}'),
  P('pikachu',    'Pikachu',    'electric', 3, 0.32, '⚡'),
  P('raichu',     'Raichu',     'electric', 4, 0.20, '⚡'),
  P('sandshrew',  'Sandshrew',  'ground',   2, 0.45, '\u{1F994}'),
  P('sandslash',  'Sandslash',  'ground',   3, 0.30, '\u{1F994}'),
  P('nidoranf',   'Nidoran♀','poison', 2, 0.45, '\u{1F407}'),
  P('nidorina',   'Nidorina',   'poison',   3, 0.32, '\u{1F407}'),
  P('nidoqueen',  'Nidoqueen',  'poison',   4, 0.18, '\u{1F451}'),
  P('nidoranm',   'Nidoran♂','poison', 2, 0.45, '\u{1F407}'),
  P('nidorino',   'Nidorino',   'poison',   3, 0.32, '\u{1F407}'),
  P('nidoking',   'Nidoking',   'poison',   4, 0.18, '\u{1F451}'),
  P('clefairy',   'Clefairy',   'fairy',    3, 0.32, '\u{1F31F}'),
  P('clefable',   'Clefable',   'fairy',    4, 0.18, '✨'),
  P('vulpix',     'Vulpix',     'fire',     3, 0.32, '\u{1F98A}'),
  P('ninetales',  'Ninetales',  'fire',     4, 0.18, '\u{1F98A}'),
  P('jigglypuff', 'Jigglypuff', 'fairy',    2, 0.45, '\u{1F3B5}'),
  P('wigglytuff', 'Wigglytuff', 'fairy',    3, 0.32, '\u{1F3B6}'),
  P('zubat',      'Zubat',      'flying',   1, 0.55, '\u{1F987}'),
  P('golbat',     'Golbat',     'flying',   2, 0.42, '\u{1F987}'),
  P('oddish',     'Oddish',     'grass',    2, 0.48, '\u{1F331}'),
  P('gloom',      'Gloom',      'grass',    3, 0.32, '\u{1F33F}'),
  P('vileplume',  'Vileplume',  'grass',    4, 0.20, '\u{1F33A}'),
  P('paras',      'Paras',      'bug',      2, 0.45, '\u{1F344}'),
  P('parasect',   'Parasect',   'bug',      3, 0.32, '\u{1F344}'),
  P('venonat',    'Venonat',    'bug',      2, 0.45, '\u{1F41E}'),
  P('venomoth',   'Venomoth',   'bug',      3, 0.32, '\u{1F98B}'),
  P('diglett',    'Diglett',    'ground',   2, 0.50, '\u{1F7EB}'),
  P('dugtrio',    'Dugtrio',    'ground',   3, 0.32, '\u{1F7EB}'),
  P('meowth',     'Meowth',     'normal',   2, 0.45, '\u{1F431}'),
  P('persian',    'Persian',    'normal',   3, 0.30, '\u{1F408}'),
  P('psyduck',    'Psyduck',    'water',    2, 0.45, '\u{1F986}'),
  P('golduck',    'Golduck',    'water',    3, 0.32, '\u{1F986}'),
  P('mankey',     'Mankey',     'fighting', 2, 0.45, '\u{1F412}'),
  P('primeape',   'Primeape',   'fighting', 3, 0.32, '\u{1F412}'),
  P('growlithe',  'Growlithe',  'fire',     3, 0.32, '\u{1F415}'),
  P('arcanine',   'Arcanine',   'fire',     4, 0.18, '\u{1F436}'),
  P('poliwag',    'Poliwag',    'water',    2, 0.45, '\u{1F4A7}'),
  P('poliwhirl',  'Poliwhirl',  'water',    3, 0.32, '\u{1F4A7}'),
  P('poliwrath',  'Poliwrath',  'water',    4, 0.18, '\u{1F4AA}'),
  P('abra',       'Abra',       'psychic',  3, 0.30, '\u{1F52E}'),
  P('kadabra',    'Kadabra',    'psychic',  4, 0.20, '\u{1F52E}'),
  P('alakazam',   'Alakazam',   'psychic',  4, 0.15, '\u{1F31F}'),
  P('machop',     'Machop',     'fighting', 3, 0.32, '\u{1F4AA}'),
  P('machoke',    'Machoke',    'fighting', 3, 0.25, '\u{1F4AA}'),
  P('machamp',    'Machamp',    'fighting', 4, 0.18, '\u{1F4AA}'),
  P('bellsprout', 'Bellsprout', 'grass',    2, 0.48, '\u{1F33F}'),
  P('weepinbell', 'Weepinbell', 'grass',    3, 0.32, '\u{1F33F}'),
  P('victreebel', 'Victreebel', 'grass',    4, 0.18, '\u{1F33A}'),
  P('tentacool',  'Tentacool',  'water',    2, 0.45, '\u{1FABC}'),
  P('tentacruel', 'Tentacruel', 'water',    3, 0.30, '\u{1FABC}'),
  P('geodude',    'Geodude',    'rock',     2, 0.50, '\u{1FAA8}'),
  P('graveler',   'Graveler',   'rock',     3, 0.32, '\u{1FAA8}'),
  P('golem',      'Golem',      'rock',     4, 0.18, '⛰️'),
  P('ponyta',     'Ponyta',     'fire',     3, 0.32, '\u{1F40E}'),
  P('rapidash',   'Rapidash',   'fire',     4, 0.18, '\u{1F40E}'),
  P('slowpoke',   'Slowpoke',   'water',    2, 0.45, '\u{1F40C}'),
  P('slowbro',    'Slowbro',    'water',    3, 0.30, '\u{1F40C}'),
  P('magnemite',  'Magnemite',  'electric', 3, 0.32, '\u{1F9F2}'),
  P('magneton',   'Magneton',   'electric', 4, 0.20, '\u{1F9F2}'),
  P('farfetchd',  "Farfetch'd", 'flying',   3, 0.32, '\u{1F986}'),
  P('doduo',      'Doduo',      'flying',   2, 0.45, '\u{1F426}'),
  P('dodrio',     'Dodrio',     'flying',   3, 0.30, '\u{1F985}'),
  P('seel',       'Seel',       'water',    3, 0.32, '\u{1F9AD}'),
  P('dewgong',    'Dewgong',    'water',    4, 0.18, '\u{1F9AD}'),
  P('grimer',     'Grimer',     'poison',   2, 0.45, '\u{1F32B}'),
  P('muk',        'Muk',        'poison',   3, 0.30, '\u{1F32B}'),
  P('shellder',   'Shellder',   'water',    2, 0.45, '\u{1F41A}'),
  P('cloyster',   'Cloyster',   'water',    3, 0.30, '\u{1F41A}'),
  P('gastly',     'Gastly',     'ghost',    2, 0.45, '\u{1F47B}'),
  P('haunter',    'Haunter',    'ghost',    3, 0.30, '\u{1F47B}'),
  P('gengar',     'Gengar',     'ghost',    4, 0.18, '\u{1F47B}'),
  P('onix',       'Onix',       'rock',     3, 0.32, '\u{1F40D}'),
  P('drowzee',    'Drowzee',    'psychic',  2, 0.45, '\u{1F634}'),
  P('hypno',      'Hypno',      'psychic',  3, 0.30, '\u{1F634}'),
  P('krabby',     'Krabby',     'water',    2, 0.45, '\u{1F980}'),
  P('kingler',    'Kingler',    'water',    3, 0.32, '\u{1F980}'),
  P('voltorb',    'Voltorb',    'electric', 2, 0.45, '\u{1F534}'),
  P('electrode',  'Electrode',  'electric', 3, 0.30, '\u{1F7E2}'),
  P('exeggcute',  'Exeggcute',  'grass',    2, 0.45, '\u{1F95A}'),
  P('exeggutor',  'Exeggutor',  'grass',    3, 0.30, '\u{1F334}'),
  P('cubone',     'Cubone',     'ground',   3, 0.32, '\u{1F480}'),
  P('marowak',    'Marowak',    'ground',   3, 0.28, '\u{1F480}'),
  P('hitmonlee',  'Hitmonlee',  'fighting', 4, 0.18, '\u{1F9B5}'),
  P('hitmonchan', 'Hitmonchan', 'fighting', 4, 0.18, '\u{1F94A}'),
  P('lickitung',  'Lickitung',  'normal',   3, 0.30, '\u{1F445}'),
  P('koffing',    'Koffing',    'poison',   2, 0.45, '☁️'),
  P('weezing',    'Weezing',    'poison',   3, 0.30, '☁️'),
  P('rhyhorn',    'Rhyhorn',    'ground',   3, 0.32, '\u{1F98F}'),
  P('rhydon',     'Rhydon',     'ground',   4, 0.18, '\u{1F98F}'),
  P('chansey',    'Chansey',    'normal',   4, 0.15, '\u{1F95A}'),
  P('tangela',    'Tangela',    'grass',    3, 0.32, '\u{1F33F}'),
  P('kangaskhan', 'Kangaskhan', 'normal',   4, 0.18, '\u{1F998}'),
  P('horsea',     'Horsea',     'water',    2, 0.45, '\u{1F40E}'),
  P('seadra',     'Seadra',     'water',    3, 0.30, '\u{1F409}'),
  P('goldeen',    'Goldeen',    'water',    2, 0.48, '\u{1F420}'),
  P('seaking',    'Seaking',    'water',    3, 0.32, '\u{1F420}'),
  P('staryu',     'Staryu',     'water',    3, 0.32, '⭐'),
  P('starmie',    'Starmie',    'water',    4, 0.18, '\u{1F31F}'),
  P('mrmime',     'Mr. Mime',   'psychic',  4, 0.18, '\u{1F921}'),
  P('scyther',    'Scyther',    'bug',      4, 0.18, '\u{1F997}'),
  P('jynx',       'Jynx',       'ice',      4, 0.18, '\u{1F48B}'),
  P('electabuzz', 'Electabuzz', 'electric', 4, 0.18, '⚡'),
  P('magmar',     'Magmar',     'fire',     4, 0.18, '\u{1F525}'),
  P('pinsir',     'Pinsir',     'bug',      4, 0.18, '\u{1F41E}'),
  P('tauros',     'Tauros',     'normal',   4, 0.18, '\u{1F402}'),
  P('magikarp',   'Magikarp',   'water',    1, 0.65, '\u{1F41F}'),
  P('gyarados',   'Gyarados',   'water',    4, 0.15, '\u{1F409}'),
  P('lapras',     'Lapras',     'water',    5, 0.10, '\u{1F432}'),
  P('ditto',      'Ditto',      'normal',   4, 0.18, '\u{1F7E3}'),
  P('eevee',      'Eevee',      'normal',   3, 0.30, '\u{1F98A}'),
  P('vaporeon',   'Vaporeon',   'water',    4, 0.18, '\u{1F30A}'),
  P('jolteon',    'Jolteon',    'electric', 4, 0.18, '⚡'),
  P('flareon',    'Flareon',    'fire',     4, 0.18, '\u{1F525}'),
  P('porygon',    'Porygon',    'normal',   4, 0.20, '\u{1F7E6}'),
  P('omanyte',    'Omanyte',    'rock',     4, 0.20, '\u{1F41A}'),
  P('omastar',    'Omastar',    'rock',     4, 0.15, '\u{1F41A}'),
  P('kabuto',     'Kabuto',     'rock',     4, 0.20, '\u{1F980}'),
  P('kabutops',   'Kabutops',   'rock',     4, 0.15, '\u{1F980}'),
  P('aerodactyl', 'Aerodactyl', 'rock',     5, 0.10, '\u{1F985}'),
  P('snorlax',    'Snorlax',    'normal',   5, 0.12, '\u{1F634}'),
  P('articuno',   'Articuno',   'ice',      5, 0.05, '❄️'),
  P('zapdos',     'Zapdos',     'electric', 5, 0.05, '⚡'),
  P('moltres',    'Moltres',    'fire',     5, 0.05, '\u{1F525}'),
  P('dratini',    'Dratini',    'dragon',   4, 0.20, '\u{1F40D}'),
  P('dragonair',  'Dragonair',  'dragon',   4, 0.15, '\u{1F409}'),
  P('dragonite',  'Dragonite',  'dragon',   5, 0.08, '\u{1F432}'),
  P('mewtwo',     'Mewtwo',     'psychic',  5, 0.04, '\u{1F31F}'),
  P('mew',        'Mew',        'psychic',  5, 0.06, '✨'),
];

// PokeAPI sprite URLs (raw GitHub) — pixel art from official games.
const SPRITE_BASE = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon';
POKEDEX.forEach((p, i) => {
  p.dex = i + 1;
  p.spriteUrl      = `${SPRITE_BASE}/${p.dex}.png`;
  p.spriteShinyUrl = `${SPRITE_BASE}/shiny/${p.dex}.png`;
});

const POKEMON_BY_ID = Object.fromEntries(POKEDEX.map(p => [p.id, p]));

// Areas: each has a spawn pool with weights. Higher weight = more common.
const AREAS = [
  {
    id: 'meadow', name: 'Pallet Meadow', emoji: '\u{1F33C}',
    bg: { sky: '#a8d8ff', ground: '#7ec850', accent: '#ffd700' },
    spawnPool: [
      { id: 'pidgey',     weight: 22 },
      { id: 'rattata',    weight: 22 },
      { id: 'caterpie',   weight: 18 },
      { id: 'weedle',     weight: 14 },
      { id: 'spearow',    weight: 10 },
      { id: 'oddish',     weight: 6  },
      { id: 'bellsprout', weight: 4  },
      { id: 'pikachu',    weight: 3  },
      { id: 'eevee',      weight: 1  },
    ],
    encounterDelay: [4000, 9000],
  },
  {
    id: 'forest', name: 'Viridian Forest', emoji: '\u{1F332}',
    bg: { sky: '#6b8e5a', ground: '#3d5a3d', accent: '#2d4a2d' },
    spawnPool: [
      { id: 'caterpie',   weight: 18 },
      { id: 'metapod',    weight: 14 },
      { id: 'weedle',     weight: 14 },
      { id: 'kakuna',     weight: 10 },
      { id: 'pidgey',     weight: 10 },
      { id: 'pidgeotto',  weight: 6  },
      { id: 'oddish',     weight: 6  },
      { id: 'bellsprout', weight: 5  },
      { id: 'butterfree', weight: 4  },
      { id: 'beedrill',   weight: 4  },
      { id: 'pikachu',    weight: 3  },
      { id: 'venonat',    weight: 3  },
      { id: 'paras',      weight: 2  },
      { id: 'bulbasaur',  weight: 1  },
    ],
    encounterDelay: [5000, 11000],
  },
  {
    id: 'lake', name: 'Cerulean Lake', emoji: '\u{1F30A}',
    bg: { sky: '#8cc8ff', ground: '#3a78b8', accent: '#5a98d8' },
    spawnPool: [
      { id: 'magikarp',   weight: 25 },
      { id: 'tentacool',  weight: 18 },
      { id: 'poliwag',    weight: 14 },
      { id: 'goldeen',    weight: 12 },
      { id: 'psyduck',    weight: 10 },
      { id: 'krabby',     weight: 8  },
      { id: 'shellder',   weight: 7  },
      { id: 'horsea',     weight: 6  },
      { id: 'staryu',     weight: 4  },
      { id: 'slowpoke',   weight: 4  },
      { id: 'seel',       weight: 3  },
      { id: 'squirtle',   weight: 1  },
      { id: 'lapras',     weight: 1  },
      { id: 'gyarados',   weight: 1  },
      { id: 'articuno',   weight: 1  },
    ],
    encounterDelay: [6000, 12000],
  },
  {
    id: 'mountain', name: 'Mt. Moon', emoji: '\u{1F304}',
    bg: { sky: '#c08aa8', ground: '#7a6a5a', accent: '#a89878' },
    spawnPool: [
      { id: 'zubat',      weight: 22 },
      { id: 'geodude',    weight: 18 },
      { id: 'sandshrew',  weight: 14 },
      { id: 'rattata',    weight: 10 },
      { id: 'diglett',    weight: 10 },
      { id: 'paras',      weight: 8  },
      { id: 'clefairy',   weight: 6  },
      { id: 'golbat',     weight: 5  },
      { id: 'graveler',   weight: 4  },
      { id: 'rhyhorn',    weight: 4  },
      { id: 'onix',       weight: 4  },
      { id: 'cubone',     weight: 3  },
      { id: 'omanyte',    weight: 1  },
      { id: 'kabuto',     weight: 1  },
      { id: 'aerodactyl', weight: 1  },
    ],
    encounterDelay: [7000, 14000],
  },
  {
    id: 'powerplant', name: 'Power Plant', emoji: '⚡',
    bg: { sky: '#3a3a4a', ground: '#5a5a4a', accent: '#3a3a3a' },
    spawnPool: [
      { id: 'magnemite',  weight: 22 },
      { id: 'voltorb',    weight: 18 },
      { id: 'pikachu',    weight: 14 },
      { id: 'grimer',     weight: 10 },
      { id: 'koffing',    weight: 10 },
      { id: 'magneton',   weight: 8  },
      { id: 'electrode',  weight: 6  },
      { id: 'electabuzz', weight: 5  },
      { id: 'raichu',     weight: 4  },
      { id: 'jolteon',    weight: 2  },
      { id: 'porygon',    weight: 1  },
      { id: 'zapdos',     weight: 1  },
    ],
    encounterDelay: [7000, 14000],
  },
  {
    id: 'tower', name: 'Pokemon Tower', emoji: '\u{1F47B}',
    bg: { sky: '#3a2a4a', ground: '#2a1a3a', accent: '#4a3a5a' },
    spawnPool: [
      { id: 'gastly',     weight: 22 },
      { id: 'zubat',      weight: 16 },
      { id: 'cubone',     weight: 14 },
      { id: 'haunter',    weight: 12 },
      { id: 'drowzee',    weight: 10 },
      { id: 'koffing',    weight: 8  },
      { id: 'marowak',    weight: 6  },
      { id: 'hypno',      weight: 5  },
      { id: 'gengar',     weight: 4  },
      { id: 'mrmime',     weight: 2  },
      { id: 'mew',        weight: 1  },
    ],
    encounterDelay: [8000, 15000],
  },
  {
    id: 'volcano', name: 'Cinnabar Volcano', emoji: '\u{1F30B}',
    bg: { sky: '#8a3a2a', ground: '#4a2a1a', accent: '#6a3a2a' },
    spawnPool: [
      { id: 'growlithe',  weight: 18 },
      { id: 'vulpix',     weight: 16 },
      { id: 'ponyta',     weight: 14 },
      { id: 'magmar',     weight: 12 },
      { id: 'rhyhorn',    weight: 10 },
      { id: 'arcanine',   weight: 6  },
      { id: 'ninetales',  weight: 6  },
      { id: 'rapidash',   weight: 5  },
      { id: 'charmander', weight: 4  },
      { id: 'flareon',    weight: 3  },
      { id: 'charmeleon', weight: 2  },
      { id: 'charizard',  weight: 1  },
      { id: 'moltres',    weight: 1  },
    ],
    encounterDelay: [8000, 16000],
  },
  {
    id: 'safari', name: 'Safari Zone', emoji: '\u{1F33F}',
    bg: { sky: '#d8c878', ground: '#a8b860', accent: '#888830' },
    spawnPool: [
      { id: 'nidoranf',   weight: 12 },
      { id: 'nidoranm',   weight: 12 },
      { id: 'venonat',    weight: 10 },
      { id: 'exeggcute',  weight: 9  },
      { id: 'paras',      weight: 8  },
      { id: 'doduo',      weight: 8  },
      { id: 'tauros',     weight: 6  },
      { id: 'kangaskhan', weight: 5  },
      { id: 'chansey',    weight: 4  },
      { id: 'tangela',    weight: 4  },
      { id: 'scyther',    weight: 3  },
      { id: 'pinsir',     weight: 3  },
      { id: 'lickitung',  weight: 3  },
      { id: 'dratini',    weight: 2  },
      { id: 'dragonair',  weight: 1  },
      { id: 'dragonite',  weight: 1  },
      { id: 'mewtwo',     weight: 1  },
    ],
    encounterDelay: [9000, 18000],
  },
];

const AREA_BY_ID = Object.fromEntries(AREAS.map(a => [a.id, a]));

const BALL_SPRITE_BASE = 'https://play.pokemonshowdown.com/sprites/itemicons';
const BALLS = [
  { id: 'afkball',    name: 'AFK Ball',     emoji: '\u{2B55}',   catchMult: 0.9, color: '#9aa6b5',
    spriteUrl: BALL_SPRITE_BASE + '/premier-ball.png' },
  { id: 'pokeball',   name: 'Poké Ball',    emoji: '\u{26AA}',   catchMult: 1.5, color: '#e85a5a',
    spriteUrl: BALL_SPRITE_BASE + '/poke-ball.png' },
  { id: 'superball',  name: 'Great Ball',   emoji: '\u{1F535}',  catchMult: 2.5, color: '#5a8ee8',
    spriteUrl: BALL_SPRITE_BASE + '/great-ball.png' },
  { id: 'hyperball',  name: 'Ultra Ball',   emoji: '\u{1F7E1}',  catchMult: 4.0, color: '#f0c040',
    spriteUrl: BALL_SPRITE_BASE + '/ultra-ball.png' },
  { id: 'masterball', name: 'Master Ball',  emoji: '\u{1F7E3}',  catchMult: 99,  color: '#a050d8',
    spriteUrl: BALL_SPRITE_BASE + '/master-ball.png' },
];

const BALL_BY_ID = Object.fromEntries(BALLS.map(b => [b.id, b]));

function _hasIvAtLeast(s, threshold) {
  return (s.caughtList || []).some(inst => {
    const total = inst.ivs.hp + inst.ivs.atk + inst.ivs.def + inst.ivs.spAtk + inst.ivs.spDef + inst.ivs.spd;
    return total / 186 >= threshold;
  });
}

const ACHIEVEMENTS = [
  { id: 'first_catch',     name: 'First Catch!',         desc: 'Catch your first Pokemon.',
    check: (s) => s.totalCatches >= 1 },
  { id: 'ten_catches',     name: 'Collector',            desc: 'Catch 10 Pokemon.',
    check: (s) => s.totalCatches >= 10 },
  { id: 'fifty_catches',   name: 'Pokemon Pro',          desc: 'Catch 50 Pokemon.',
    check: (s) => s.totalCatches >= 50 },
  { id: 'hundred_catches', name: 'Centurion',            desc: 'Catch 100 Pokemon.',
    check: (s) => s.totalCatches >= 100 },
  { id: 'all_meadow',      name: 'Meadow Explored',      desc: 'Catch every Pokemon in Pallet Meadow.',
    check: (s) => AREA_BY_ID.meadow.spawnPool.every(sp => (s.pokedex[sp.id] || 0) > 0) },
  { id: 'all_forest',      name: 'Forest Master',        desc: 'Catch every Pokemon in Viridian Forest.',
    check: (s) => AREA_BY_ID.forest.spawnPool.every(sp => (s.pokedex[sp.id] || 0) > 0) },
  { id: 'all_lake',        name: 'Lake Diver',           desc: 'Catch every Pokemon in Cerulean Lake.',
    check: (s) => AREA_BY_ID.lake.spawnPool.every(sp => (s.pokedex[sp.id] || 0) > 0) },
  { id: 'all_mountain',    name: 'Mountain Climber',     desc: 'Catch every Pokemon in Mt. Moon.',
    check: (s) => AREA_BY_ID.mountain.spawnPool.every(sp => (s.pokedex[sp.id] || 0) > 0) },
  { id: 'caught_legendary',name: 'Legend Hunter',        desc: 'Catch a legendary Pokemon.',
    check: (s) => Object.keys(s.pokedex).some(id => POKEMON_BY_ID[id] && POKEMON_BY_ID[id].rarity === 5) },
  { id: 'pokedex_50',      name: 'Pokedex Quarter',      desc: 'Discover 50 different Pokemon.',
    check: (s) => Object.keys(s.pokedex).length >= 50 },
  { id: 'pokedex_100',     name: 'Pokedex Half',         desc: 'Discover 100 different Pokemon.',
    check: (s) => Object.keys(s.pokedex).length >= 100 },
  { id: 'pokedex_complete',name: 'Pokedex Complete',     desc: 'Discover all 151 Pokemon.',
    check: (s) => POKEDEX.every(p => (s.pokedex[p.id] || 0) > 0) },
  { id: 'efficient',       name: 'Efficient',            desc: 'Reach a 50% catch rate (min. 20 throws).',
    check: (s) => s.totalThrows >= 20 && s.totalCatches / s.totalThrows >= 0.5 },
  { id: 'iv_excellent',    name: 'Top Genetics',         desc: 'Catch a Pokemon with IV total >= 80%.',
    check: (s) => _hasIvAtLeast(s, 0.80) },
  { id: 'iv_perfect',      name: 'Genetic Marvel',       desc: 'Catch a Pokemon with IV total >= 95%.',
    check: (s) => _hasIvAtLeast(s, 0.95) },
  { id: 'shiny_hunter',    name: 'Shiny Hunter',         desc: 'Catch a shiny Pokemon.',
    check: (s) => (s.caughtList || []).some(i => i.isShiny) },
  { id: 'perfect_stop_10', name: 'Precision Master',     desc: 'Hit the sweet spot 10 times.',
    check: (s) => (s.totalPerfectStops || 0) >= 10 },
];


// ---------- Moves (Gen 1 attacks) ----------
function M(id, name, type, power, acc, cat) { return { id, name, type, power, acc, cat, color: tc(type) }; }
const MOVES = [
  M('tackle','Tackle','normal',40,100,'physical'),
  M('scratch','Scratch','normal',40,100,'physical'),
  M('pound','Pound','normal',40,100,'physical'),
  M('quick_attack','Quick Attack','normal',40,100,'physical'),
  M('body_slam','Body Slam','normal',85,100,'physical'),
  M('hyper_beam','Hyper Beam','normal',150,90,'special'),
  M('mega_kick','Mega Kick','normal',120,75,'physical'),
  M('slash','Slash','normal',70,100,'physical'),
  M('headbutt','Headbutt','normal',70,100,'physical'),
  M('bite','Bite','normal',60,100,'physical'),
  M('cut','Cut','normal',50,95,'physical'),
  M('growl','Growl','normal',0,100,'status'),
  M('leer','Leer','normal',0,100,'status'),
  M('tail_whip','Tail Whip','normal',0,100,'status'),
  M('sand_attack','Sand Attack','normal',0,100,'status'),
  M('ember','Ember','fire',40,100,'special'),
  M('flamethrower','Flamethrower','fire',90,100,'special'),
  M('fire_blast','Fire Blast','fire',120,85,'special'),
  M('fire_punch','Fire Punch','fire',75,100,'physical'),
  M('fire_spin','Fire Spin','fire',35,85,'special'),
  M('water_gun','Water Gun','water',40,100,'special'),
  M('bubble_beam','Bubble Beam','water',65,100,'special'),
  M('surf','Surf','water',90,100,'special'),
  M('hydro_pump','Hydro Pump','water',110,80,'special'),
  M('waterfall','Waterfall','water',80,100,'physical'),
  M('vine_whip','Vine Whip','grass',45,100,'physical'),
  M('razor_leaf','Razor Leaf','grass',55,95,'physical'),
  M('solar_beam','Solar Beam','grass',120,100,'special'),
  M('petal_dance','Petal Dance','grass',90,100,'special'),
  M('absorb','Absorb','grass',20,100,'special'),
  M('thunder_shock','Thunder Shock','electric',40,100,'special'),
  M('thunderbolt','Thunderbolt','electric',90,100,'special'),
  M('thunder','Thunder','electric',110,70,'special'),
  M('thunder_punch','Thunder Punch','electric',75,100,'physical'),
  M('thunder_wave','Thunder Wave','electric',0,100,'status'),
  M('ice_beam','Ice Beam','ice',90,100,'special'),
  M('blizzard','Blizzard','ice',120,70,'special'),
  M('ice_punch','Ice Punch','ice',75,100,'physical'),
  M('aurora_beam','Aurora Beam','ice',65,100,'special'),
  M('karate_chop','Karate Chop','fighting',50,100,'physical'),
  M('low_kick','Low Kick','fighting',50,100,'physical'),
  M('submission','Submission','fighting',80,80,'physical'),
  M('seismic_toss','Seismic Toss','fighting',80,100,'physical'),
  M('poison_sting','Poison Sting','poison',15,100,'physical'),
  M('sludge','Sludge','poison',65,100,'special'),
  M('acid','Acid','poison',40,100,'special'),
  M('toxic','Toxic','poison',0,90,'status'),
  M('earthquake','Earthquake','ground',100,100,'physical'),
  M('dig','Dig','ground',80,100,'physical'),
  M('bone_club','Bone Club','ground',65,85,'physical'),
  M('wing_attack','Wing Attack','flying',60,100,'physical'),
  M('fly','Fly','flying',90,95,'physical'),
  M('gust','Gust','flying',40,100,'special'),
  M('peck','Peck','flying',35,100,'physical'),
  M('drill_peck','Drill Peck','flying',80,100,'physical'),
  M('confusion','Confusion','psychic',50,100,'special'),
  M('psychic','Psychic','psychic',90,100,'special'),
  M('psybeam','Psybeam','psychic',65,100,'special'),
  M('hypnosis','Hypnosis','psychic',0,60,'status'),
  M('string_shot','String Shot','bug',0,95,'status'),
  M('twin_needle','Twin Needle','bug',25,100,'physical'),
  M('pin_missile','Pin Missile','bug',25,95,'physical'),
  M('leech_life','Leech Life','bug',80,100,'physical'),
  M('rock_throw','Rock Throw','rock',50,90,'physical'),
  M('rock_slide','Rock Slide','rock',75,90,'physical'),
  M('lick','Lick','ghost',30,100,'physical'),
  M('shadow_ball','Shadow Ball','ghost',80,100,'special'),
  M('night_shade','Night Shade','ghost',50,100,'special'),
  M('dragon_rage','Dragon Rage','dragon',40,100,'special'),
  M('twister','Twister','dragon',40,100,'special'),
  M('sweet_kiss','Sweet Kiss','fairy',0,75,'status'),
  M('disarming_voice','Disarming Voice','fairy',40,100,'special'),
];
const MOVE_BY_ID = Object.fromEntries(MOVES.map(m => [m.id, m]));
const UNIVERSAL_MOVES = ['tackle','scratch','pound','quick_attack','leer','growl'];
function buildLearnset(pokemon) {
  const fromType = MOVES.filter(m => m.type === pokemon.type).map(m => m.id);
  const set = new Set([...UNIVERSAL_MOVES, ...fromType]);
  if ((pokemon.rarity || 1) >= 4) {
    set.add('hyper_beam'); set.add('body_slam'); set.add('slash');
  }
  return Array.from(set);
}
function rollMoveset(pokemon) {
  const pool = buildLearnset(pokemon);
  const shuffled = [...pool].sort(() => Math.random() - 0.5);
  const count = (pokemon.rarity || 1) >= 4 ? 4 : (2 + Math.floor(Math.random() * 3));
  return shuffled.slice(0, Math.min(count, shuffled.length));
}

const LEGENDARY_IDS = new Set(['mewtwo','mew','articuno','zapdos','moltres','dragonite','snorlax','lapras','aerodactyl','gyarados','dragonair','kabutops','omastar','alakazam','machamp']);
function isLegendaryPokemon(id) { return LEGENDARY_IDS.has(id); }
function xpForLevelUp(level) { return level * 100; }

window.GameData = { POKEDEX, POKEMON_BY_ID, AREAS, AREA_BY_ID, BALLS, BALL_BY_ID, ACHIEVEMENTS, LEGENDARY_IDS, isLegendaryPokemon, xpForLevelUp, MOVES, MOVE_BY_ID, buildLearnset, rollMoveset, TYPE_COLORS };
